apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kpilot-ai.fullname" . }}-secrets
  labels:
    {{- include "kpilot-ai.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.secrets.openaiEndpoint }}
  OPENAI_ENDPOINT: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.secrets.geminiApiKey }}
  GEMINI_API_KEY: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.secrets.xaiApiKey }}
  XAI_API_KEY: {{ . | b64enc | quote }}
  {{- end }}
